export const levelOne = [
"Lo que yo espero hacer es...",
"Creo que soy bastante bueno en...",
"Me felicitaron porque...",
"Mi trabajo puede ser difícil porque...",
"La forma en que mi trabajo va bien para mi es...",
"Lo que me gusta de este trabajo es...",
"Aprendí mucho cuando...",
"Quiero aprender más sobre...",
"Lo que hice desde la última vez que nos vimos es...",
"En lo que estoy trabajando ahora es...",
"La razón por la que puedo ser bloqueado es...",
"Puedo ver mi progreso cuando...",
"Lo que haré antes de la próxima vez que nos veamos es...",
"Puedo mejorar la calidad de mi trabajo si...",
"No puedo ser yo mismo cuando...",
"La razón por la que me importa es...",
"Lo que más necesito es...",
"Mis valores importantes son...",
"Me motiva...",
"Mi propósito a largo plazo es...",
"La razón por la que estoy en riesgo es...",
"Veo la oportunidad de...",
"No quiero sentirme responsable de...",
"Quiero ser responsable de...",
"Salgo de mi zona de confort cuando...",
"Lo que no me atrevo a hacer todavía es...",
"Me estoy ayudandoa mí mismo cuando...",
"Puedo deleitar a los demás al...",
"Lo que me gustaría cambiar en mí mismo es...",
"Estoy orgulloso de mí mismo cuando...",
"Una pregunta que debería hacer es...",
"Lo que creo pero no puedo probar es...",
"Lo que parece estar pasando es...",
"La forma en que me ha sorprendido es...",
"Necesito más claridad porque...",
"No he hecho todo lo que puedo porque...",
"Podría sentirme más energizado por...",
"Una cosa que debería dejar de hacer es...",
"El paso más audaz para mí sería...",
"La razón por la que a veces me siento feliz es...",
];

export const levelTwo = [
  "La forma en que nosotros hacemos las cosas bien es...",
"Lo que yo espero de nuestras conversaciones es...",
"Lo bueno de nuestras conversaciones es...",
"Nosotros fuimos felicitados porque...",
"Nuestras conversaciones pueden ser difíciles porque...",
"Lo que nosotroshemos aprendido es...",
"De lo que nosotros podemos aprender más es...",
"Lo que nosotros deberíamos estar haciendo ahora es...",
"Lo que nosotros hicimos desde nuestra última sesión es...",
"Lo que agradezco en nuestras sesiones es...",
"La razón por la que nuestra conversación puede ser bloqueada es...",
"Puedo ver que nosotros progresamos cuando...",
"Lo que nosotros deberíamos hacer antes de nuestra próxima sesión es...",
"Nosotros podemos mejorar la calidad de nuestras sesiones al...",
"Nuestra conversación no es óptima cuando...",
"La razón por la que nos importa es...",
"Lo que más necesitan nuestras conversaciones es...",
"Nuestros valores importantes son...",
"Nosotros estamos motivados por...",
"Nuestro propósito a largo plazo es...",
"La razón por la que nuestras conversaciones están en riesgo es...",
"Nuestras conversaciones tienen la oportunidad de...",
"Nosotros no deberíamos ser responsables de...",
"Nosotros somos responsables de...",
"Nosotros salimos de nuestras zonas de confort cuando...",
"Lo que todavía nosotors no nos atrevemos a hacer es...",
"Podría apoyarte cuando...",
"Puedes ayudarme con...",
"Lo que me gustaría cambiar en nuestras sesiones es...",
"Estoy orgulloso de nosotros cuando...",
"Una pregunta que debes hacer es...",
"Lo que nosotros creemos pero no podemos probar es...",
"Lo que está emergiendo en nuestra conversación es...",
"La forma en que nuestras sesiones han sido sorprendentes es...",
"Nosotros necesitamos más claridad porque...",
"Nosotros no hemos hecho todo lo posible porque...",
"Nosotros podríamos sentirnos más energizados por...",
"Una cosa que nosotros podemos dejar de hacer es...",
"La razón por la que nuestras sesiones pueden sentirse bien es...",
"El paso más audaz para nosotros sería...",
];

export const levelThree = [
"Lo que espero de el equipo es...",
"Lo que aprecio de el equipo es...",
"La organización fue felicitada porque...",
"Nuestra organización puede resultar difícil porque...",
"La forma en que el trabajo en el equipo va bien es...",
"La organización ha aprendido a...",
"Lo que el equipo debería aprender es...",
"Lo que el equipo debería estar haciendo ahora es...",
"Desde nuestra sesión anterior, el equipo ha...",
"La organización es muy buena en...",
"La razón por la que nuestra organización puede ser bloqueada...",
"Puedo ver que el equipo progresa cuando...",
"Antes de nuestra próxima sesión, el equipo debería...",
"La organización no se desempeña bien cuando...",
"La organización debería mejorar la calidad mediante...",
"La razón por la que a el equipo le importa es...",
"Lo que más necesita el equipo es...",
"Los valores importantes en el equipo son...",
"El propósito a largo plazo de el equipo es...",
"La organización parece estar motivada por...",
"La razón por la que el equipo está en riesgo es...",
"La organización tiene la oportunidad de...",
"La organización no se hace responsable de...",
"La organización es responsable de...",
"La organización está fuera de su zona de confort cuando...",
"Lo que el equipo no se atreve a hacer es...",
"Estoy deleitando a otros en el equipo cuando...",
"Lo que cambiaría en el equipo es...",
"La organización debería apoyarme cuando...",
"Estoy orgulloso de nuestra organización cuando...",
"Una pregunta que el equipo debería hacer es...",
"Lo que el equipo cree pero no puede probar es...",
"Lo que está surgiendo en el equipo es...",
"La forma en que el equipo se ha sorprendido es...",
"La organización necesita más claridad porque...",
"La organización no ha hecho todo lo posible porque...",
"La organización podría estar más energizada por...",
"Una cosa que el equipo podría dejar de hacer es...",
"La razón por la que el equipo puede sentirse feliz es...",
"El paso más audaz para el equipo sería...",
];

export const levelFour = [
"Lo que los clientes pueden esperar de nosotros es...",
"Un buen cambio entre los clientes es...",
" Nuestros clientes han aprendido a...",
" Lo que aprecio de los clientes es...",
"Nuestros clientes pueden ser difíciles porque...",
"Lo que hacen bien nuestros clientes es...",
"Lo que nuestros clientes deben aprender es...",
"Lo que nuestros clientes deberían estar haciendo ahora es...",
"Después de nuestra sesión anterior, nuestros clientes han...",
"Nuestros clientes deben ser elicitados porque...",
"La razón por la que nuestros clientes pueden ser bloqueados es...",
"Puedo ver a los clientes progresando cuando...",
"Antes de nuestra próxima sesión, nuestros clientes deberían...",
"Nuestros clientes esperan calidad cuando...",
"Nuestros clientes no pueden desempeñarse bien cuando...",
" Lo que más necesitan nuestros clientes es...",
"Los valores importantes para los clientes son...",
"El propósito a largo plazo de nuestros clientes es...",
"Nuestros clientes parecen estar motivados por...",
"La razón por la que nuestros clientes importan es...",
"La razón por la que nuestros clientes están en riesgo es...",
"Existe una oportunidad para nuestros clientes cuando...",
"Nuestros clientes no son responsables de...",
"Nuestros clientes están fuera de su zona de confort cuando...",
"Nuestros clientes pueden ser responsables de...",
"Lo que los clientes no se atreven a hacer es...",
"Estamos deleitando a nuestros clientes cuando...",
"Nuestros clientes podrían apoyarnos cuando...",
"Estoy orgulloso de nuestros clientes cuando...",
" Lo que cambiaría de los clientes es...",
"Una pregunta que nuestros clientes deben hacer es...",
"Lo que los clientes creen pero no pueden probar es...",
"Lo que está surgiendo entre los clientes es...",
"La forma en que nuestros clientes se han sorprendido es...",
"Nuestros clientes necesitan más claridad porque...",
"Nuestros clientes no han hecho todo lo posible porque...",
"Nuestros clientes podrían estar más motivados por...",
"Una cosa que nuestros clientes deberían dejar de hacer es...",
"El paso más audaz para nuestros clientes sería...",
"La razón por la que nuestros clientes pueden sentirse bien es...",
];
